project_id = "uwipbqbqhdlylvubzdto"

[functions.profile-evaluation]
verify_jwt = false

[functions.realtime-interview]
verify_jwt = false

[functions.create-notification]
verify_jwt = false

[functions.generate-404-image]
verify_jwt = false
